### PR TITLE
Various template fixes

### PR DESCRIPTION
**Pull request by wfdd**
Attribute/dict access doesn't work inside ``blocktrans``.

### CODE REVIEW

**Comment by wfdd** [comment]
For instance [[1]](https://candidates.democracyclub.org.uk/election/sp.r.2016-05-05/party-list/gss:S17000009/party:1):

> Oh no! We don’t know of any candidates from for Member of the Scottish Parliament for Central Scotland for the 2016 Scottish Parliament Election (Regions) yet.

That should be:

> Oh no! We don’t know of any candidates from **Beaconsfield Independent Electors Association** for Member of the Scottish Parliament for Central Scotland for the 2016 Scottish Parliament Election (Regions) yet.

**Comment by wfdd** [comment]
I've pushed another commit in the same vein.  The site name was missing from the first sentence in `/tasks/` (see https://candidates.democracyclub.org.uk/tasks/).

**Comment by wfdd** [comment]
Okay, I've pushed another unrelated fix so I'm renaming this to something suitably vague.

**Comment by mhl** [comment]
:+1:  This all looks good, thank-you - I've rebased and then merged to keep the history simpler.

**Pull request closed without merging**
