### PR TITLE
Add ordering to extra fields

### PR DESCRIPTION
**Pull request by wfdd**

### CODE REVIEW

**Comment by mhl** [comment]
Thanks @wfdd - this is great, but could you also add the new `order` parameter to the serializer of ExtraField for the API?

**Comment by wfdd** [comment]
whoops, done that now.

**Comment by mhl** [comment]
:+1: Looks good

**Comment by mhl** [comment]
I've rebased this and then merged, hope that's OK

**Comment by wfdd** [comment]
Yep, thanks.

**Pull request closed without merging**
