### PR TITLE
Various UK updates

### PR DESCRIPTION
**Pull request by symroe**
Sorry that this isn't very neat, but these are some of the various updates I've made to the UK site that don't fall into any other PR.

### CODE REVIEW

**Comment by struan** [comment]
Looks good.

**Comment by struan** [comment]
Although I notice that the first two commits in this are already merged in so possibly they should be removed before I merge this branch.

**Comment by symroe** [comment]
Whoops, I've removed those two now – getting mixed up with maintaining a load of branches! :)

**Comment by wfdd** [comment]
The changes in `_finder.scss` broke the front page styling of all the other sites.

**Pull request merged**
