### PR TITLE
Refuse to start if a party ID maps to multiple parties

### PR DESCRIPTION
**Pull request by mhl**
If the party data has non-unique party IDs, this will create all kinds
of problems; it's best to raise an Exception if this is the case so that
the data can be fixed.

### CODE REVIEW

**Comment by lizconlan** [comment]
:+1: (commit message grumble aside!)

**Comment by mhl** [comment]
Thanks, @lizconlan, I've fixed that. I won't merge this until I've heard back from @martinszy and tried it on our staging server.

**Comment by martinszy** [comment]
Looks awesome, let's test it.

**Comment by martinszy** [comment]
I've run ar_elections_2015_create_popit_organizations and I end up with duplicate parties, plus a lot of mongo errors on popit

PUT /api/v0.1/organizations/hcdn 200 68.334 ms - 390
MongoError: E11000 duplicate key error index: popitdev_ynr3-argentina.organizations.$_id_  dup key: { : "hcsn" }
    at Object.toError (/home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:636:22
    at Server.Base._callHandler (/home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at MongoReply.parseBody (/home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at EventEmitter.emit (events.js:95:17)
    at null.<anonymous> (/home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (/home/faras/www/yo/yoquierosaber/popit/node_modules/popit-api/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)

I don't think this is a problem, since I'm essencialy duplicating them.

- Do we have to delete all organizations from popit to have a clean one?
Then we'll have to re-recreate all memberships again.

- Can we update the script so it updates the ID using name matching?
I think this would generate the least amount of work.

**Comment by mhl** [comment]
@martinszy You shouldn't need to delete the organizations from PopIt - the `ar_elections_2015_create_popit_organizations` will update existing organizations based on their ID.

I've just tried this myself and it worked fine. There are duplicate organizations in the sense that, for instance, there are six organizations called "Partido Obrero", for example, but each of those is the party of that name for a particular province (indicated by its `territory` attribute). There's only one of these in each party set for each of those provinces, so you'll only ever see the party name once in a party select box.

The only obvious disadvantage I can see with this is that they would currently have separate party pages, if we were to enable the party pages again. That could be worked around, though.

You could replace them with a single party that's in the national party set, but that seems wrong since the point is that you can only vote for that party in certain provinces.

For reference, here are the duplicate party names I found:

      6         "name": "Partido Obrero",

      5         "name": "Partido Popular",

      4         "name": "Nueva Dirigencia",

      3         "name": "Uni\u00f3n por la Libertad",
      3         "name": "Uni\u00f3n del Centro Democr\u00e1tico",
      3         "name": "Partido Proyecto Popular",
      3         "name": "Partido del Trabajo y la Equidad",
      3         "name": "Partido del Campo Popular",
      3         "name": "Partido Autonomista",
      3         "name": "Frente H.A.C.E.R. por el Progreso Social",

      2         "name": "Proyecto Sur",
      2         "name": "Patria Grande",
      2         "name": "Partido Tercera Posicion (P3P)",
      2         "name": "Partido Dem\u00f3crata",
      2         "name": "Partido de los Trabajadores Socialistas",
      2         "name": "Movimiento Norte Grande",
      2         "name": "Movimiento Integraci\u00f3n Latinoamericana de Expresi\u00f3n Social (M.I.L.E.S)",
      2         "name": "Movimiento Integraci\u00f3n Latinoamericana de Expresi\u00f3n Social",
      2         "name": "Encuentro Popular",

And there are some instances where it looks as if the names of different parties should be made consistent with each other:

      1 "Union del Centro Democratico"
      2 "Unión del Centro Democrático"
      1 "Partido Unión del Centro Democrático"

      1 "Partido Proyecto Popular (P.P.)"
      3 "Partido Proyecto Popular"

      1 "Frente H.A.C.E.R por el Progreso Social"
      3 "Frente H.A.C.E.R. por el Progreso Social"

      1 "Partido Tercera Posicion"
      1 "Partido Tercera Posición (P3P)"
      2 "Partido Tercera Posicion (P3P)"

      2 "Movimiento Integración Latinoamericana de Expresión Social"
      2 "Movimiento Integración Latinoamericana de Expresión Social (M.I.L.E.S)"

However, as I said above, I don't think these should be big issues.

**Comment by martinszy** [comment]
Hi Mark, sorry for being 10 days late in my response.
I remember we talked about parties having an territories array... what ever
happened to that?
Can we bring that idea back?

Also, I agree with the repeated names, but maybe they are registered with
different names in different provinces... should we respect the official
name or try to improve it?

2015-08-04 10:30 GMT-03:00 Mark Longair <notifications@github.com>:

> @martinszy <https://github.com/martinszy> You shouldn't need to delete
> the organizations from PopIt - the
> ar_elections_2015_create_popit_organizations will update existing
> organizations based on their ID.
>
> I've just tried this myself and it worked fine. There are duplicate
> organizations in the sense that, for instance, there are six organizations
> called "Partido Obrero", for example, but each of those is the party of
> that name for a particular province (indicated by its territory
> attribute). There's only one of these in each party set for each of those
> provinces, so you'll only ever see the party name once in a party select
> box.
>
> The only obvious disadvantage I can see with this is that they would
> currently have separate party pages, if we were to enable the party pages
> again. That could be worked around, though.
>
> You could replace them with a single party that's in the national party
> set, but that seems wrong since the point is that you can only vote for
> that party in certain provinces.
>
> For reference, here are the duplicate party names I found:
>
>   6         "name": "Partido Obrero",
>
>   5         "name": "Partido Popular",
>
>   4         "name": "Nueva Dirigencia",
>
>   3         "name": "Uni\u00f3n por la Libertad",
>   3         "name": "Uni\u00f3n del Centro Democr\u00e1tico",
>   3         "name": "Partido Proyecto Popular",
>   3         "name": "Partido del Trabajo y la Equidad",
>   3         "name": "Partido del Campo Popular",
>   3         "name": "Partido Autonomista",
>   3         "name": "Frente H.A.C.E.R. por el Progreso Social",
>
>   2         "name": "Proyecto Sur",
>   2         "name": "Patria Grande",
>   2         "name": "Partido Tercera Posicion (P3P)",
>   2         "name": "Partido Dem\u00f3crata",
>   2         "name": "Partido de los Trabajadores Socialistas",
>   2         "name": "Movimiento Norte Grande",
>   2         "name": "Movimiento Integraci\u00f3n Latinoamericana de Expresi\u00f3n Social (M.I.L.E.S)",
>   2         "name": "Movimiento Integraci\u00f3n Latinoamericana de Expresi\u00f3n Social",
>   2         "name": "Encuentro Popular",
>
> And there are some instances where it looks as if the names of different
> parties should be made consistent with each other:
>
>   1 "Union del Centro Democratico"
>   2 "Unión del Centro Democrático"
>   1 "Partido Unión del Centro Democrático"
>
>   1 "Partido Proyecto Popular (P.P.)"
>   3 "Partido Proyecto Popular"
>
>   1 "Frente H.A.C.E.R por el Progreso Social"
>   3 "Frente H.A.C.E.R. por el Progreso Social"
>
>   1 "Partido Tercera Posicion"
>   1 "Partido Tercera Posición (P3P)"
>   2 "Partido Tercera Posicion (P3P)"
>
>   2 "Movimiento Integración Latinoamericana de Expresión Social"
>   2 "Movimiento Integración Latinoamericana de Expresión Social (M.I.L.E.S)"
>
> However, as I said above, I don't think these should be big issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mysociety/yournextrepresentative/pull/490#issuecomment-127612146>
> .
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by mhl** [comment]
Just a few quick notes, since I'm just about to go away on leave for a week:

* In the case where repeated names just have minor differences (e.g. missing accents, whether the party abbreviation is included) I think they should be unified.
* Using a `territories` array of strings instead of a `territory` string would be a nice way of representing this in the `all-parties-from-popit.json` file.

**Comment by mhl** [comment]
@martinszy I've created a separate issue for de-duplicating the parties - I think this should be merged even though it doesn't deal with that, since it fixes the duplicate IDs.

**Pull request merged**
